// <auto-generated />
namespace FAST_FOOD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class _UdUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_UdUser));
        
        string IMigrationMetadata.Id
        {
            get { return "202511192022053__UdUser"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
