// <auto-generated />
namespace FAST_FOOD.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class AddTaiKhoan : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddTaiKhoan));
        
        string IMigrationMetadata.Id
        {
            get { return "202511100921071_AddTaiKhoan"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
